var res = {
    ui:'res/ui.plist',
    uiImg:'res/ui.png',
    gameList:'res/gameList.plist',
    gameListImg:'res/gameList.png',
    catIndex:'res/catIndex.plist',
    catIndexImg:'res/catIndex.png',
    boomFrames:'res/boom.plist',
    boomImg:'res/boom.png',
    mainBg:'res/mainBg.jpg',
    endBg:'res/endBg.jpg',
    font:'res/font.fnt',
    fontImg:'res/font.png',
    scoreFont:'res/scoreFont.fnt',
    scoreFontImg:'res/scoreFont.png',
    audio_claps1:'res/audio/claps1.m4a',
    audio_claps2:'res/audio/claps1.m4a',
    audio_claps3:'res/audio/claps1.m4a',
    audio_claps4:'res/audio/claps1.m4a',
    audio_claps5:'res/audio/claps1.m4a',
    audio_starGain:'res/audio/starGain.m4a',
    audio_tap:'res/audio/tap.m4a',
    audio_timePick:'res/audio/timePick.m4a',
    audio_timerStop:'res/audio/timerStop.m4a',
    audio_counter:'res/audio/counter.m4a',
    audio_counterLast:'res/audio/counterLast.m4a'
},gameResources = checkRes(res);